version: "3.8"

services:
  mysqldemo:
    image: mysql:8.0
    container_name: mysqldemo
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: coremarker
      MYSQL_DATABASE: demologin
    volumes:
      - mysql_data:/var/lib/mysql

  demo-login:
    build: .
    depends_on:
      - mysqldemo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldemo:3306/demologin?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: coremarker

volumes:
  mysql_data: